version: '2'
services:
  web:
    image: webdevops/php-apache:7.1
    ports:
      - "443:443"
    volumes:
      - .:/app
    environment:
      - php.short_open_tag=On
      - WEB_DOCUMENT_ROOT=/app/html
  # db:
  #   image: mysql:5.6.22
  #   environment:
  #     - MYSQL_ALLOW_EMPTY_PASSWORD=yes
